// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlvmsyflghbqgnjpfpgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsdm1zeWZsZ2hicWduanBmcGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njk0MzMsImV4cCI6MjA2NTA0NTQzM30.csOr9jyluk4mSR2Vl-an5mKbtip3slFi8MTaG9pFD10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);